# Generated by Django 5.1.2 on 2024-10-12 18:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.PositiveIntegerField()),
                ('goles_visitante', models.PositiveIntegerField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_locales', to='equipos.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='equipos.equipo')),
                ('mvp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp', to='jugadores.jugador')),
            ],
        ),
    ]
