# Generated by Django 5.1.2 on 2024-10-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_jugador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, default='jugador.jpg', null=True, upload_to='jugadores'),
        ),
    ]
