# Generated by Django 5.1.2 on 2024-10-13 17:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta', models.CharField(choices=[('amarilla', 'amarilla'), ('roja', 'roja')], max_length=10, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('fecha_sancion', models.DateField(default=datetime.date.today)),
                ('observaciones', models.TextField(max_length=200, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amonestaciones', to='jugadores.jugador')),
            ],
        ),
    ]
