# Generated by Django 5.1.2 on 2024-10-12 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Blanco', 'blanco'), ('Color', 'color')], max_length=30)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('jugadores', models.ManyToManyField(related_name='jugadores', to='jugadores.jugador')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
