# Generated by Django 5.1.2 on 2024-10-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(related_name='equipos', to='jugadores.jugador'),
        ),
    ]
